repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=5000']    # Sets limit to 5 MB
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-added-large-files
        exclude: '(\.pdf|\.whl|\.ipynb)$'
      - id: check-added-large-files
